[package]
name = "SSRRR"
version = "0.1.0"
edition = "2024"

[dependencies]
rosu-map = "0.2.1"
tokio = "1.47.1"

[[example]]
name = "star_rating_calculator"
path = "examples/star_rating_calculator.rs"
